spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

server:
  port: 8072

management:
    tracing:
        sampling:
            probability: 1.0
        exporter:
            zipkin:
                enabled: true
                endpoint: http://localhost:9411/api/v2/spans
