spring:
    application:
        name: customer-service
    datasource:
        url: jdbc:postgresql://localhost:5432/customerdb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka   
        
server:
    port: 8003


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,trace
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
    propagation:
      enabled: true

logging:
  level:
      org:
          springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg traceId=%X{traceId}%n"
