spring:
    application:
        name: customer-service
    datasource:
        url: jdbc:postgresql://localhost:5432/customerdb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka   
        
server:
    port: 8003
    
logging:
    level:
        org:
            springframework: INFO
