spring:
    application:
        name: eureka-server-dev
server:
    port: 8761

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka    
    
logging:
    level:
        org:
            springframework: INFO
