spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:postgresql://localhost:5432/inventorydb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka   
        
server:
    port: 8005
    
logging:
    level:
        org:
            springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,trace
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
