spring:
    application:
        name: payment-service
    datasource:
        url: jdbc:postgresql://localhost:5432/paymentdb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
    redis:
        host: localhost
        port: 6379

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka   
        
server:
    port: 8006
    
logging:
    level:
        org:
            springframework: INFO
