spring:
    application:
        name: product-catalog-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: productdb

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka    
        
server:
    port: 8001
    
logging:
    level:
        org:
            springframework: INFO
            
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,trace
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
             
