spring:
    application:
        name: product-catalog-service-dev
    datasource:
        url: jdbc:postgresql://localhost:5432/productdb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka    
        
server:
    port: 8001
    
logging:
    level:
        org:
            springframework: INFO
            

             
