spring:
    application:
        name: product-catalog-service-dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: productdb

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka    
        
server:
    port: 8001
    
logging:
    level:
        org:
            springframework: INFO
            

             
