spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/productdb
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
server:
    port: 8001
    
logging:
    level:
        org:
            springframework: INFO
            

             
